// TODO: Complete Transfer Manager test
// test transferManagerSpend() {
//   let tx = 
//     Transaction {
//       ..placeholder,
//       inputs: [userIn],
//       outputs: [userOut, rec1],
//       reference_inputs: [registryRef, globalRef, userRef, recRef]
//       extra_signatories: [user],
//     }  

//   transferManager(registry, owner, None, Spend, oref, tx)?
// }

// Multi Recipient test
