// use cardano/transaction.{Transaction, placeholder}
// use v1/user_state

// test mintUserState() {
//   user_state.userStateManager.mint()
// }

// test burnUserState() {
//   and {
//     user_state.userStateManager.mint(),
//     user_state.userStateManager.spend(),
//   }
// }

// test makeAdmin() {
//   user_state.userStateManager.mint()
// }

// test makeKyc() {
//   user_state.userStateManager.mint()
// }

// test makeBlacklist() {
//   user_state.userStateManager.mint()
// }

// test makeFreeze() {
//   user_state.userStateManager.mint()
// }
